[build]
  publish = ""
  functions = "dist"
  base = ""
  command = "npm run build"

  [functions]
    external_node_modules = ["express"]
    node_bundler = "esbuild"
  
  [[redirects]]
    force = true
    from = "/api/*"
    status = 200
    to = "/dist/:splat"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
